site_name: Erida Documentation
repo_url: https://github.com/Vecortys/Erida-14-DOCS
repo_name: Erida-14-DOCS

theme:
  name: material
  language: ru
  palette:
    - scheme: slate
      toggle: { icon: material/brightness-4, name: Switch to light mode }
      primary: deep purple
    - scheme: default
      toggle: { icon: material/brightness-7, name: Switch to dark mode }
      primary: deep purple
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

plugins:
  - search
  - git-revision-date-localized
  - git-authors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

nav:
  - Главная: main.md

  - Прототипы:
    - YAML: prototypes/yaml.md
    - Базовый Прототип: prototypes/base_proto.md
    - Типы Прототипов: prototypes/types_proto.md
    

