site_name: Erida Documentation
site_url: https://vecortys.github.io/Erida-14-DOCS/
repo_url: https://github.com/dead-space-server/space-erida-14
repo_name: Erida-14-DOCS

theme:
  name: material
  language: ru
  palette:
    - scheme: slate
      toggle: { icon: material/brightness-4, name: Switch to light mode }
      primary: deep purple
    - scheme: default
      toggle: { icon: material/brightness-7, name: Switch to dark mode }
      primary: deep purple
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.sections
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - content.tooltips

plugins:
  - search
  - git-revision-date-localized
  - git-authors
  - glightbox
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - attr_list

extra_css:
  - assets/css/extra.css

nav:
  - Главная: index.md
  - Среда Разработки: dev_env.md
  - Политика Изменений: base_rules.md

  - Прототипы:
    - Обучение:
      - YAML: prototypes/yaml.md
      - Базовый Прототип: prototypes/base_proto.md
      - Типы Прототипов: prototypes/types_proto.md
    

